FROM php:8.5.6-fpm

LABEL maintainer="Henrique Felix <hfelixmiguell@gmail.com>"
ARG PHP_VERSION=8.5.6

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

# Changing DocumentRoot
ENV APACHE_DOCUMENT_ROOT=/var/www/public

# Configure locale.
ARG LOCALE=POSIX
ENV LC_ALL=${LOCALE}

RUN apt-get update && apt-get install -y --no-install-recommends \
    default-mysql-client \
    libpq-dev \
    libicu-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install redis
RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl pdo pdo_mysql \
    && docker-php-ext-enable pdo_mysql redis

COPY ./php.ini /usr/local/etc/php/conf.d
COPY ./pool.conf /usr/local/etc/php-fpm.d/
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.



WORKDIR /var/www
