FROM php:8.4.21-fpm

LABEL maintainer="Henrique Felix <hfelixmiguell@gmail.com>"
ARG PHP_VERSION=8.4.21

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

# Changing DocumentRoot
ENV APACHE_DOCUMENT_ROOT /var/www/public

# Configure locale.
ARG LOCALE=POSIX
ENV LC_ALL ${LOCALE}

## Give full access to the /tmp directory for the www-data user, otherwise some packages will fail to install
RUN chmod 1777 /tmp

WORKDIR /var/www
USER root
