services:

  myproject-opencode:
        image: devfelixh/opencode-v1:latest
        container_name: myproject-opencode
        restart: unless-stopped
        stdin_open: true
        tty: true
        user: "1000:1000"
        group_add:
            - "${DOCKER_GID}" ## Add to your .profile: export DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
        env_file:
            - .opencode.env
        ports:
            - 3000:3000
        environment:
            - HF_TOKEN=${HF_TOKEN} ## HUGGINFACE TOKEN
            - DOCKER_GID=${DOCKER_GID}
        volumes:
            - .:/var/www/project
            - ~/.ssh:/home/www-data/.ssh:ro ## ONLY READ ONLY ACCESS TO THE SSH local
            - /var/run/docker.sock:/var/run/docker.sock
            - opencode-config:/home/www-data/
        working_dir: /var/www/project
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - project-network
            
volumes:
    opencode-config: