FROM python:3.11.16-slim@sha256:9c900dea9e8fb7e16277c179b555cc72d29a352dbc33cff48ad5a0412fd5bfc7

ENV GO_VERSION=1.23.0
ENV GOPATH="/home/www-data/go"
ENV HOME=/home/www-data

ENV PATH="/usr/local/go/bin:${GOPATH}/bin:${HOME}/.opencode/bin:${PATH}"
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV NODE_NO_WARNINGS=1
ENV NODE_OPTIONS="--no-warnings"

### CONFIGURABLE ENV VARS ###
ENV OPENCODE_MAIN_MODEL=""
ENV OPENCODE_WEB_SERVER_HOST=""
ENV UNSLOTH_STUDIO_API_KEY=""
ENV GITHUB_ACCESS_TOKEN_MCP=""
ENV CONTEXT7_API_KEY=""

## OPENWIKI ###
ENV OPENWIKI_PROVIDER="openai-compatible"
ENV OPENAI_COMPATIBLE_API_KEY=llama
ENV OPENAI_COMPATIBLE_BASE_URL=""
ENV OPENWIKI_MODEL_ID=""
ENV LANGSMITH_API_KEY=""
ENV OPENWIKI_TELEMETRY_DISABLED=1
ENV DO_NOT_TRACK=1

## OPENCHAMBER
ENV OPENCHAMBER_UI_PASSWORD=1234
ENV OPENCHAMBER_PORT=3000

ENV PHP_CONTAINER=""
ENV OPENCODE_CONTAINER_NAME=""


RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    ripgrep \
    fd-find \
    jq \
    procps \
    lsof \
    wget \
    unzip \
    tree \
    gh \
    openssh-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=docker:cli /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker/buildx-bin:latest /buildx /usr/libexec/docker/cli-plugins/docker-buildx
COPY --from=docker/compose-bin:latest /docker-compose /usr/libexec/docker/cli-plugins/docker-compose

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY docker/opencode-entrypoint.sh /etc/opencode-entrypoint.sh
RUN chmod +x /etc/opencode-entrypoint.sh

RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nsolid && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" | tar -C /usr/local -xzf -

RUN curl -fsSL https://bun.sh/install | bash

RUN curl --proto '=https' --tlsv1.2 -LsSf https://github.com/j178/prek/releases/download/v0.4.13/prek-installer.sh | sh

RUN go install github.com/eljakani/ward@latest

RUN mkdir -p /home/www-data /var/www/project /ms-playwright ${GOPATH} && \
    groupmod -g 1000 www-data && \
    usermod -u 1000 -g www-data -d /home/www-data www-data

RUN ln -s /bin/true /usr/local/bin/xdg-open

RUN npm install -g playwright@latest && \
    playwright install --with-deps chromium chrome --force

RUN mkdir -p /home/www-data/.npm
RUN mkdir -p /home/www-data/.cache/composer/
RUN mkdir -p /home/www-data/.opencode/

RUN npm install -g mermaid jsdom
RUN npm install -g @openchamber/web
RUN curl -fsSL https://opencode.ai/install | bash

RUN chown -R www-data:www-data /home/www-data /ms-playwright /tmp /usr/local/bin ${GOPATH} 

## Map local files to this container folder.
WORKDIR /var/www/project

USER www-data

ENTRYPOINT ["/etc/opencode-entrypoint.sh"]

CMD ["python3"]