FROM php:8.4.21-fpm

LABEL maintainer="Henrique Felix <hfelixmiguell@gmail.com>"
ARG PHP_VERSION=8.4.21

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

# Changing DocumentRoot
ENV APACHE_DOCUMENT_ROOT /var/www/public

# Configure locale.
ARG LOCALE=POSIX
ENV LC_ALL ${LOCALE}

COPY ./laravel.ini /usr/local/etc/php/conf.d
COPY ./pool.conf /usr/local/etc/php-fpm.d/
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini

RUN chmod -R www-data:www-data /tmp

WORKDIR /var/www
