FROM php:8.5.6-cli

LABEL maintainer="Henrique Felix <hfelixmiguell@gmail.com>"
ARG PHP_VERSION=8.5.6

# Set Environment Variables
ENV DEBIAN_FRONTEND=noninteractive

# Configure locale.
ARG LOCALE=POSIX
ENV LC_ALL=${LOCALE}

RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y nano; \
    apt-get install -y --no-install-recommends \
    curl \
    libmemcached-dev \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    libicu-dev \
    default-mysql-client \
    libfreetype6-dev \
    libssl-dev \
    libwebp-dev \
    libxpm-dev \
    libmcrypt-dev \
    libonig-dev; \
    curl -sL https://deb.nodesource.com/setup_24.x | bash - ; \
    apt install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

RUN pecl install redis
RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl pdo pdo_mysql \
    && docker-php-ext-enable pdo_mysql redis

WORKDIR /var/www

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN mkdir -p /var/www/

RUN chown -R www-data:www-data /var/www /tmp